- .env.example
- .github/workflows/main.yml
- README.md
- jest.config.js
- jest.integration.config.js
- package.json
- project-management/planning/the-dream-team.md
- project-management/startup.xml
- project-management/task-management/doing.md
- project-management/task-management/done.md
- project-management/task-management/todo.md
- setup_env.sh
- src/config/version.ts
- src/index.ts
- src/server.ts
- src/types/config.ts
- tests/integration/server.test.ts
- tests/unit/server.test.ts
Added PAT-based authentication handler with configuration validation and tests: 
- Added configuration validation for organization URL and PAT 
- Implemented PAT-based authentication using Azure DevOps Node API 
- Added unit tests for server initialization and configuration 
- Added integration tests for live Azure DevOps connection 
- Improved setup script with dynamic PAT expiration 
- Added detailed error handling and logging 
- All tests passing
> Implement PAT-based authentication handler with tests

- docs/azure-identity-authentication.md
- package-lock.json
- package.json
- project-management/task-management/doing.md
- project-management/task-management/todo.md
- src/test-azure-identity.js
- src/test-azure-identity.ts
Completed research on DefaultAzureCredential and AzureCliCredential for Azure DevOps authentication. Created documentation for implementation approach.
> Research Azure Identity Authentication

- project-management/task-management/doing.md
- project-management/task-management/todo.md
- src/operations/workitems.ts
- src/server.ts
- tests/unit/operations/workitems-update-coverage.test.ts
- tests/unit/operations/workitems/update-work-item.test.ts
This pull request introduces the implementation of the `update_work_item` handler for the Azure DevOps MCP server, along with comprehensive tests and necessary schema and interface updates. The key changes include the addition of the `update_work_item` handler, the creation of the corresponding schema and options, and the implementation of unit tests to ensure the functionality works as expected.
* Added `updateWorkItem` function to handle updating work items in `src/operations/workitems.ts`. This function constructs a JSON patch document based on provided options and updates the work item using Azure DevOps API.
* Introduced `UpdateWorkItemSchema` and `UpdateWorkItemOptions` to define the schema and options for updating a work item in `src/operations/workitems.ts`. …
> Implement update_work_item handler

- project-management/task-management/doing.md
- project-management/task-management/done.md
- project-management/task-management/todo.md
- tests/unit/operations/workitems/list-work-items.test.ts
- tests/unit/server-list-work-items.test.ts
This pull request includes several updates related to task management and unit tests for the Azure DevOps MCP server. The most important changes include the completion and documentation of specific tasks, the removal of tasks from the to-do list, and the addition of unit tests for the `list_work_items` handler.
Task Management Updates:
* [`project-management/task-management/doing.md`](diffhunk://#diff-28f5504d524a3a8d9ce89517168b8a561add549e41b5254b5dd5073c9af83e45L2-L15): Removed Task 2.4, which involved implementing the `update_work_item` handler with tests.
* [`project-management/task-management/done.md`](diffhunk://#diff-7484241519f66fa4247380bd305cbaebabf20bcbe3511f8ee56482c0947bbf0bR2-R13): Added Task 2.6 and Task 2.4 to the list of completed tasks, documenting the implementation …
> Implement list_work_items handler with tests

- .github/workflows/release.yml
This pull request includes a small change to the `.github/workflows/release.yml` file. The change adds the `tag_name` parameter to the `jobs:` section, using the version output from the `package-version` step.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R58): Added `tag_name: v${{ steps.package-version.outputs.version }}` to the `jobs:` section to specify the tag name for the release.
> fix: add tag_name parameter to GitHub release action

- .github/workflows/release.yml
This pull request includes a change to the GitHub Actions workflow for releasing the project. The change adds a step to publish the package to npm.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R53-R57): Added a step to publish the package to npm with the necessary environment variable for authentication.
> Add npm publish to release.yml

- .husky/pre-commit
- src/features/work-items/create-work-item/feature.spec.int.ts
- src/features/work-items/create-work-item/feature.ts
- src/features/work-items/schemas.ts
- src/features/work-items/types.ts
- src/server.ts
This pull request introduces the ability to create a child work item with a parent-child relationship in the Azure DevOps integration. The changes span multiple files and add support for specifying a parent work item when creating a new work item.
The most important changes include:
* Added a new test case to `src/features/work-items/create-work-item/feature.spec.int.ts` to verify the creation of a child work item with a parent-child relationship. This test ensures that the relationship is correctly established and validated.
* Modified `createWorkItem` function in `src/features/work-items/create-work-item/feature.ts` to handle the addition of a parent relationship if a `parentId` is provided in the options.
* Updated `CreateWorkItemSchema` in `src/features/work-items/schemas.ts` to …
> fix: add parent-child relationship support for createWorkItem

- docs/tools/work-items.md
- project-management/task-management/doing.md
- project-management/task-management/done.md
- project-management/task-management/todo.md
- src/features/work-items/get-work-item/feature.spec.int.ts
- src/features/work-items/get-work-item/feature.ts
- src/features/work-items/list-work-items/feature.ts
- src/features/work-items/schemas.ts
- src/server.ts
Enhanced the get_work_item tool to default to WorkItemExpand.All when no specific fields are requested, providing more complete information in the response.
> Allow get_work_item to default to expand all

- project-management/task-management/done.md
- project-management/task-management/drafts/issue-104-create-test-plan-draft.md
- project-management/task-management/drafts/issue-104-create-test-plan-final.md
- project-management/task-management/drafts/issue-104-github-issue-content.md
- project-management/task-management/drafts/issue-105-github-issue-content.md
- project-management/task-management/drafts/issue-105-publish-artifact-draft.md
- project-management/task-management/drafts/issue-105-publish-artifact-final.md
- src/features/search/index.ts
- src/features/search/schemas.ts
- src/features/search/search-work-items/feature.spec.int.ts
- src/features/search/search-work-items/feature.spec.unit.ts
- src/features/search/search-work-items/feature.ts
- src/features/search/search-work-items/index.ts
- src/features/search/types.ts
- src/server.ts
This PR implements the search_work_items handler to enable searching across work items in Azure DevOps projects. The implementation includes:
- New types and schemas for work item search
- Implementation of the search_work_items handler
- Unit tests for the handler
- Integration tests for the handler
- Updates to server.ts to register the new tool
Closes #96
> Implement search_work_items handler with tests

- docs/tools/search.md
- src/features/search/schemas.ts
- src/features/search/search-code/feature.spec.unit.ts
- src/features/search/search-code/feature.ts
- src/features/search/search-wiki/feature.spec.unit.ts
- src/features/search/search-wiki/feature.ts
- src/features/search/search-work-items/feature.spec.unit.ts
- src/features/search/search-work-items/feature.ts
- src/features/search/types.ts
This PR addresses issue #126 by making the projectId parameter optional in global search features. When projectId is not provided, the search will be performed across the entire Azure DevOps organization instead of a specific project. This enables the MCP client to respond to queries about code examples across all projects in the organization.
> feat: Make projectId optional in search features for organization-wide search

- project-management/task-management/done.md
- src/features/search/search-code/feature.spec.unit.ts
- src/features/search/search-code/feature.ts
This PR fixes a bug in the search_code feature where content is displayed as '[Object Object]' when the includeContent parameter is set to true. It also adds a limit to the number of results when includeContent is enabled to prevent timeouts.
- Modified the enrichResultsWithContent function to properly handle NodeJS.ReadableStream objects
- Fixed parameter conflict in getItemContent API call that was causing 'Cannot specify an item "path" as well as "scopePath"' error
- Updated parameter order to use proper versionDescriptor object instead of passing changeId directly
- Added automatic limit of 10 results when includeContent is enabled to prevent timeouts
- Updated all tests to match the new parameter signature
- Added tests to verify limiting behavior
- Added comprehensive unit tests to …
> fix: correct [Object Object] display in search_code includeContent

- src/features/users/get-me/feature.spec.int.ts
- src/features/users/get-me/feature.spec.unit.ts
- src/features/users/get-me/feature.ts
Fixed a bug with the getMe feature where displayName and email were empty strings. Updated implementation to use direct profile properties according to the Azure DevOps API documentation and enhanced tests to verify non-empty values.
> fix: getMe profile bug

- .github/workflows/main.yml
- src/features/work-items/list-work-items/feature.spec.int.ts
Resolves #139 by adding explicit permissions to the main.yml workflow file. Following the principle of least privilege, I've set 'contents: read' permission which is the minimal permission required for this workflow that only needs to read repository contents to run tests and checks.
> Fix code scanning alert - Workflow does not contain permissions

- README.md
- docs/tools/README.md
- docs/tools/repositories.md
- docs/tools/resources.md
- src/server.ts
This pull request introduces a new tool for retrieving file or directory content from a Git repository in the Azure DevOps MCP server. The most important changes include adding the `get_file_content` tool, updating the relevant documentation, and modifying the server implementation to handle this new tool.
* **Documentation Updates**:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R161): Added `get_file_content` to the list of available tools.
* [`docs/tools/repositories.md`](diffhunk://#diff-3b9f3adb4a807a38eb123b6218a2a1054093512497c4608eaace3a208b28ea9fR282-R416): Added detailed documentation for the `get_file_content` tool, including its description, parameters, response, error handling, example usage, implementation details, and …
> feat: restore get_file_content tool and update documentation

- src/server.spec.e2e.ts
- src/server.ts
This pull request introduces new tests and functionality to support parameterless tools in the Azure DevOps server. The changes include adding unit and end-to-end tests for the `get_me` and `list_organizations` tools and updating the server to handle these tools without requiring arguments.
* [`src/server.spec.e2e.ts`](diffhunk://#diff-4c57badd5d811739d41b29197a7eb3b2a4dfd0d210e0d67ec2afdaed785fc1c0R170-R210): Added end-to-end tests to verify that `list_organizations` and `get_me` can be called without arguments and return valid JSON responses.
* [`src/server.spec.unit.ts`](diffhunk://#diff-0a8a21b3bec340d89ed4d2eac2f9317db2a0b1f75a05efe725d1f3434544f13eR1-R103): Added unit tests to verify that parameterless tools can be called without arguments and that tools requiring arguments throw …
> fix: allow parameterless tools to be called without arguments

- docs/tools/repositories.md
- src/features/repositories/get-all-repositories-tree/__snapshots__/feature.spec.unit.ts.snap
- src/features/repositories/get-all-repositories-tree/feature.spec.int.ts
- src/features/repositories/get-all-repositories-tree/feature.spec.unit.ts
- src/features/repositories/get-all-repositories-tree/feature.ts
- src/features/repositories/get-all-repositories-tree/index.ts
- src/features/repositories/get-all-repositories-tree/schema.ts
- src/features/repositories/get-file-content/schema.ts
- src/features/repositories/index.ts
- src/features/repositories/schemas.ts
- src/features/repositories/types.ts
- src/server.ts
Closes #150. This PR adds the get_all_repositories_tree tool that displays a hierarchical tree view of files and directories across multiple Azure DevOps repositories within a project, based on their default branches. The implementation follows the specifications in issue #150 and supports filtering by repository name pattern and file pattern, as well as limiting the traversal depth.
> feat(repositories): add get_all_repositories_tree tool

- src/features/wikis/get-wikis/feature.spec.int.ts
- src/features/wikis/get-wikis/feature.spec.unit.ts
- src/features/wikis/get-wikis/feature.ts
- src/features/wikis/get-wikis/handler.ts
- src/features/wikis/get-wikis/index.ts
- src/features/wikis/get-wikis/schema.ts
- src/features/wikis/index.ts
- src/server.ts
This pull request introduces a new feature for retrieving wikis from Azure DevOps projects or organizations. It includes the implementation of the `getWikis` function, unit and integration tests, schema validation, and integration with the Azure DevOps server. Below are the key changes grouped by theme:
* Added the `getWikis` function in `src/features/wikis/get-wikis/feature.ts` to fetch wikis from a specific project or organization using the Azure DevOps API. It handles errors and supports both project-level and organization-level queries.
* Added unit tests in `src/features/wikis/get-wikis/feature.spec.unit.ts` to validate the behavior of the `getWikis` function, including handling API errors and resource not found scenarios.
* Added integration tests in …
> feat(wikis): implement `get_wikis` tool

- README.md
- docs/tools/wiki.md
- src/features/wikis/get-wiki-page/feature.spec.int.ts
- src/features/wikis/get-wiki-page/feature.spec.unit.ts
- src/features/wikis/get-wiki-page/feature.ts
- src/features/wikis/get-wiki-page/index.ts
- src/features/wikis/get-wiki-page/schema.ts
- src/server.ts
- Add `get_wiki_page` functionality to retrieve content from a specific wiki page in Azure DevOps.
- Introduce schema validation for input parameters using `zod`.
- Update server integration to support the new tool.
- Create comprehensive documentation for the `get_wiki_page` tool.
- Implement unit and integration tests to ensure functionality and error handling.
This enhancement expands the capabilities of the Azure DevOps server for wiki management.
> feat(wikis): implement `get_wiki_page` tool

- src/features/work-items/schemas.ts
This PR addresses issue #179 by adding guidance in the schema description for adding comments to work items. It clarifies that when using the `System.History` field in `additionalFields`, comments should be formatted as HTML.
- Updated the description for `additionalFields` in the `UpdateWorkItemSchema` to include guidance about HTML formatting for the System.History field
- This helps the agent understand the expected format for comments, preventing issues with plain text comments appearing incorrectly in Azure DevOps
I've tested this change in my personal Azure DevOps environment against both story and bug work item types, confirming that:
1. The guidance is clear in the schema description
2. When the agent follows the guidance it will then format comments as HTML, it seems to do this …
> Fix #179: Add guidance for HTML formatting in System.History field

- README.md
- docs/tools/README.md
- docs/tools/pull-requests.md
- package.json
- src/features/pull-requests/index.ts
- src/features/pull-requests/schemas.ts
- src/features/pull-requests/tool-definitions.ts
- src/features/pull-requests/types.ts
- src/features/pull-requests/update-pull-request/feature.spec.int.ts
- src/features/pull-requests/update-pull-request/feature.spec.unit.ts
- src/features/pull-requests/update-pull-request/feature.ts
- src/features/pull-requests/update-pull-request/index.ts
- src/features/wikis/get-wiki-page/feature.spec.int.ts
- src/server.ts
This PR introduces a new feature: the `update_pull_request` tool for the Azure DevOps MCP server. This tool allows users to programmatically update various properties of an existing pull request, including title, description, status, draft state, reviewers, and linked work items.
---
- **Feature Implementation**
- New `update_pull_request` tool with full support for updating pull request metadata, reviewers, and work item links.
- Full unit test coverage for the new feature.
- **Documentation**
- Added `update_pull_request` to the main `README.md` under Pull Request Tools.
- Updated `docs/tools/README.md` to include `update_pull_request` in the Pull Request Tools section.
- Ensured the tool is referenced and discoverable in all relevant documentation indices.
- **Schema**
- Added a clean, …
> feat(pull-requests): Add `update_pull_request` Tool for Azure DevOps MCP Server

- docs/tools/pull-requests.md
- src/features/pull-requests/add-pull-request-comment/feature.spec.int.ts
- src/features/pull-requests/get-pull-request-comments/feature.spec.int.ts
- src/features/pull-requests/index.spec.unit.ts
- src/features/pull-requests/index.ts
- src/features/pull-requests/list-pull-requests/feature.spec.int.ts
- src/features/pull-requests/list-pull-requests/feature.spec.unit.ts
- src/features/pull-requests/list-pull-requests/feature.ts
- src/features/pull-requests/schemas.ts
- src/features/pull-requests/types.ts
This PR fixes issue #196 by implementing proper pagination for the list-pull-requests feature to prevent infinite loops.
- Added default value of 10 for the `top` parameter in `ListPullRequestsSchema`
- Added new `skip` parameter for pagination in schema and types
- Modified the `listPullRequests` function signature to return pagination metadata
- Updated the call to `gitApi.getPullRequests` with the correct parameter order
- Added logic to determine if there are more results and warning message for truncated results
- Updated documentation with pagination examples and warnings
- Updated tests to verify pagination functionality
- Added unit tests for pagination functionality
- Updated integration tests to work with the new response format
- Manually tested to verify the infinite loop …
> Fix: Implement pagination for list-pull-requests to prevent infinite loop

- src/features/users/get-me/feature.spec.unit.ts
- src/features/users/get-me/feature.ts
Fixes #210 by adding support for URLs of the form `org_name.visualstudio.com`
> Support the legacy URL format.

- src/features/users/get-me/feature.ts
- src/utils/environment.ts
Hi 
I’ve updated the `getOrgNameFromUrl` logic to handle both cloud and on-prem Azure DevOps URLs:
1. **Cloud URL** (`dev.azure.com`)
```ts
const devMatch = url.match(/https?:\/\/dev\.azure\.com\/([^/]+)/);
if (devMatch) return devMatch[1];
```
2. **On-prem/custom server** (only if URL contains "azure")
```ts
const fallbackMatch = url.match(/https?:\/\/[^/]+\/([^/]+)/);
return fallbackMatch ? fallbackMatch[1] : 'unknown-organization';
```
3. **Anything else** returns `"unknown-organization"` immediately.
**Behavior examples:**
| Input URL                                                 | Output                   |
| --------------------------------------------------------- | ------------------------ |
| `undefined`                                               | `unknown-organization`   | …
>  improve org name extraction from url

- docs/tools/pull-requests.md
- src/features/pull-requests/get-pull-request-comments/feature.spec.int.ts
- src/features/pull-requests/get-pull-request-comments/feature.spec.unit.ts
- src/features/pull-requests/get-pull-request-comments/feature.ts
Add the following fields to the response. #226 
1. filePath: The file path corresponding to the comment (if applicable).
2. lineNumber: The line number in the file corresponding to the comment (if applicable).
> enhanced the get-pull-request-comments tool

- src/features/wikis/create-wiki-page/feature.spec.int.ts
- src/features/wikis/create-wiki-page/feature.spec.unit.ts
- src/features/wikis/create-wiki-page/feature.ts
- src/features/wikis/create-wiki-page/index.ts
- src/features/wikis/create-wiki-page/schema.ts
- src/features/wikis/index.ts
- src/features/wikis/tool-definitions.ts
Adds a new feature 'create_wiki_page' to allow you to create new wiki pages in Azure DevOps.
The feature includes:
* Input schema for specifying organization, project, wiki ID, page path, and content.
* Core logic to call the Azure DevOps API (PUT request to /_apis/wiki/wikis/{wikiIdentifier}/pages?path={path}).
* Unit tests to verify API call parameters and error handling.
* Integration tests that use the CI environment's real Azure DevOps connection to verify end-to-end functionality.
* Helper utilities for loading test environment variables and cleaning up test wiki pages.
The new functionality is defined in 'tool-definitions.ts' and exported appropriately.
All tests are now passing:
- Unit tests: ✅
- Integration tests: ✅
- End-to-end tests: ✅
- Build checks: ✅
Closes #183
> feat: implement create_wiki_page feature for Azure DevOps wiki API integration
